### ISSUE TITLE
how to get the matrix label of https://noble.gs.washington.edu/proj/schic-topic-model/？

### ISSUE THREAD

**Issue by junmeiW** [khj3017/schic-topic-model#3]
Hi Hyeon-Jin,
   I'm a beginner in bioinfomatics, and I want to learn about scHiC. So  I downloaded some scHic data from [4dn](https://data.4dnucleome.org/) provided in your paper, and preprocessed them as [combinatorialHiC](https://github.com/VRam142/combinatorialHiC) . Next , I want to map  between the matrix and the label, but found that [GM12878-IMR90.R1.labeled](https://noble.gs.washington.edu/proj/schic-topic-model/data/matrix_labels/GM12878-IMR90.R1.labeled) not available.

Sorry for troubling you, but could you please  upload a effective **GM12878-IMR90.R1.labeled** file? 

Thanks!!!

**Comment by skelviper** [comment]
> Hi Hyeon-Jin,
> I'm a beginner in bioinfomatics, and I want to learn about scHiC. So I downloaded some scHic data from [4dn](https://data.4dnucleome.org/) provided in your paper, and preprocessed them as [combinatorialHiC](https://github.com/VRam142/combinatorialHiC) . Next , I want to map between the matrix and the label, but found that [GM12878-IMR90.R1.labeled](https://noble.gs.washington.edu/proj/schic-topic-model/data/matrix_labels/GM12878-IMR90.R1.labeled) not available.
> 
> Sorry for troubling you, but could you please upload a effective **GM12878-IMR90.R1.labeled** file?
> 
> Thanks!!!

Hi junmeiW:
same problem met,
link : https://noble.gs.washington.edu/proj/schic-topic-model/data/matrix_labels/GM12878-IMR90.R1.labeled
got a 404 error, could you upload that file or tell me how to get that?
Thanks!!!

**Comment by skelviper** [comment]
https://noble.gs.washington.edu/proj/schic-topic-model/data/input/cell_labels_rep.txt

this seems work.

**Comment by khj3017** [comment]
Hello,

I fixed the link so you should be able to download the file. Sorry for the
inconvenience.

Best,
Hyeon-Jin
